# Generated by Django 2.2 on 2019-04-14 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20190415_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='i_captain',
            new_name='is_captain',
        ),
    ]
