# Generated by Django 2.1.7 on 2019-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_auto_20190415_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position_in_field',
            field=models.CharField(choices=[('Goalkeeper', 'gk'), ('Defender', 'df'), ('HalfDefender', 'hd'), ('Striker', 'st')], max_length=120),
        ),
    ]
