# Generated by Django 2.2 on 2019-05-01 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20190422_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='first_team_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_team', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='gamescore',
            name='second_team_relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='teams.Team'),
        ),
    ]
