# Generated by Django 2.2 on 2019-05-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0010_auto_20190501_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamescore',
            name='first_team',
        ),
        migrations.RemoveField(
            model_name='gamescore',
            name='second_team',
        ),
    ]
